### ISSUE TITLE
AttributeError: 'LightFM' object has no attribute 'add_item_feature_dictionary'

### ISSUE THREAD

**Issue by hbudyanto** [lyst/lightfm-paper#1]
I attempted to re-run movielens individual experiment : `ipython -- experiments/movielens/model.py --ids --cold --split 0.2`, however i got this following error : 
  `79`
  `80     if not cf_model and not lsiup_model:`
`---> 81         model.add_item_feature_dictionary(features.feature_ids, check=False)`
`82         features.add_latent_representations(model.item_features)`
`83`
AttributeError: 'LightFM' object has no attribute 'add_item_feature_dictionary`

I further checked the declaration 'add_item_feature_dictionary" and yet could find where it located. Can anyone tell me what's going wrong with this?

**Comment by maciejkula** [comment]
This method has been removed from LightFM. You can find it in the history at this commit or earlier: https://github.com/lyst/lightfm/commit/155c3f2a0f71dc3c996bae29d16e7ab8f676514f

**Comment by hbudyanto** [comment]
Thank you @maciejkula for such prompt response. I am relatively new to this package, haven't explored much of it. Could you give me a hint on how I could still perform MF with item features on this experiment? Any advice would be appreciated

**Comment by maciejkula** [comment]
No problem.

If you'd like to run the files in this repo, the easiest way would be to clone LightFM, check out the commit I mentioned, and install it.

Alternatively, you could try running the examples included with the current versions of LightFM. These are included [here](https://github.com/lyst/lightfm/blob/master/examples/stackexchange/hybrid_crossvalidated.ipynb) and [here](https://github.com/lyst/lightfm/blob/master/examples/movielens/example.ipynb).

**Comment by hbudyanto** [comment]
Excellent! once again, many thanks for the tips
